[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "mxnet_example"
version = "0.1.0"
description = "MXNet example with MNIST and CNN"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
flwr = "1.6.0"
mxnet = "1.9.1"
numpy = "1.23.1"
