[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "flwr_opacus"
version = "0.1.0"
description = "Differentially Private Federated Learning with Opacus and Flower"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
flwr = ">=1.0,<2.0"
opacus = "1.4.0"
torchvision = "0.15.2"
