name: Build docker client image

on:
  workflow_dispatch:
    inputs:
      flwr-version:
        description: "Version of Flower e.g. (1.7.0)."
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-client-images:
    name: Build client images
    uses: ./.github/workflows/_docker-build.yml
    # run only on default branch when using it with workflow_dispatch
    if: github.ref_name == github.event.repository.default_branch
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    with:
      namespace-repository: flwr/client
      file-dir: src/docker/client
      build-args: |
        FLWR_VERSION=${{ github.event.inputs.flwr-version }}
        BASE_IMAGE_TAG=py${{ matrix.python-version }}-ubuntu22.04
      tags: |
        ${{ github.event.inputs.flwr-version }}-py${{ matrix.python-version }}-ubuntu22.04
        ${{ github.event.inputs.flwr-version }}
        latest
    secrets:
      dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
