name: Release nightly

on:
  schedule:
    - cron: "0 23 * * *"

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  release_nightly:
    runs-on: ubuntu-22.04
    name: Nightly
    if: github.repository == 'adap/flower'
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Release nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          ./dev/publish-nightly.sh
